### ISSUE TITLE
How is wallet security guaranteed for Electron app?

### ISSUE THREAD

**Issue by paulvi** [terra-money/station-electron#17]
When using browser extension private key (aka seed phrase) security is guaranteed by browser

How is wallet security guaranteed for Electron app? Is that information stored encrypted and not possible for malware to copy that info.

![image](https://user-images.githubusercontent.com/1614482/128315516-c9f243e5-db79-473f-8861-3983fca100ef.png)

**Comment by simcheolhwan** [comment]
Electron app stores encrypted like the extension.

**Comment by paulvi** [comment]
Where is data saved to ? 

https://medium.com/cameron-nokes/how-to-store-user-data-in-electron-3ba6bf66bc1e

I check `~/Library/Application\ Support/` and `~` and don't see any Terra, .terra folders

**Comment by hanjukim** [comment]
@paulvi Terra Station?

**Comment by paulvi** [comment]
@hanjukim  Terra Station electron app, as this repository.

**Comment by hanjukim** [comment]
@paulvi I meant `Terra Station` directory in Application Support
