### ISSUE TITLE
1.2 new icon is oversized for macos

### ISSUE THREAD

**Issue by manuhank** [terra-money/station-electron#22]
The new icon is lacking margins and so it seems oversized compared to standar macos icons
<img width="509" alt="Captura de Pantalla 2022-01-20 a la(s) 11 55 36" src="https://user-images.githubusercontent.com/19393548/150363095-22fc6ad4-3a1f-4014-b48a-9d8b9955de14.png">

**Comment by hanjukim** [comment]
It is working in progress
